---
  - hosts: localhost
    
    vars:
       
    tasks:
       - name: Read-write git checkout from github
         ansible.builtin.git:
           repo: 'git@github.com:jonathanmdp/Automate-submodules.git'
           dest: .
           archive: /tmp/ansible-examples.zip

