---
  - hosts: localhost
    
    vars:
       
    tasks:
       - name: Read-write git checkout from github
         ansible.builtin.git:
           repo: 'git@github.com:jonathanmdp/Automate-submodules.git'
           dest: .
           #archive: /tmp/ansible-examples.zip

       - name: Just ensuring the repo checkout exists
         ansible.builtin.git:
           repo: 'git@github.com:jonathanmdp/Automate-submodules.git'
           dest: ~/teste
           update: no           
           clone: yes
           recursive: yes

       - name: shell
         #shell: 'git remote add upstream git@github.com:jonathanmdp/Automate-submodules.git'
         shell: git add teste.yml  
       - name: checkout
         shell: git checkout master
       - name: push
         shell: git push origin master
         